# Generated by Django 5.2.11 on 2026-02-28 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Curso')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Sigla/Código')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
            ],
        ),
        migrations.AddField(
            model_name='guardian',
            name='cep',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='guardian',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='guardian',
            name='phone',
            field=models.CharField(default='0000000000', max_length=20, verbose_name='Telefone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guardian',
            name='state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='cep',
            field=models.CharField(default='00000-000', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='city',
            field=models.CharField(default='Centro', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='neighborhood',
            field=models.CharField(default='Cidade', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='number',
            field=models.CharField(default='UF', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.CharField(default='SN', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guardian',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardians',
            field=models.ManyToManyField(related_name='students', to='students.guardian', verbose_name='Responsáveis'),
        ),
        migrations.AlterField(
            model_name='student',
            name='medical_notes',
            field=models.TextField(blank=True, verbose_name='Observações Médicas'),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.course', verbose_name='Curso'),
        ),
    ]
