# Generated by Django 5.2.11 on 2026-02-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_course_guardian_cep_guardian_city_guardian_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default='0000000000', max_length=20, verbose_name='Telefone'),
        ),
    ]
