# Generated by Django 6.0.2 on 2026-02-28 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-registration_number']},
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Número da Parcela')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Pago')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Data do Pagamento')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='students.student')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
