# Generated by Django 6.0.2 on 2026-02-27 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academics.enrollment'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='period',
            field=models.IntegerField(choices=[(1, '1º Bimestre'), (2, '2º Bimestre'), (3, '3º Bimestre'), (4, '4º Bimestre')]),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('enrollment', 'subject', 'period')},
        ),
    ]
